package promn.dao.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
* Class generated by hbm2java
* 
*           The class Class
*/

@Entity(name="Clazz")
@Table(name = "Class")
public class Clazz implements Serializable {

	private static final long serialVersionUID = 1L;

	/** The id of the class */
	private int id;
	
	/** The name of the class */
	private String semester;
	
	/** The room of the class */
	private String room;
	
	/** Subject of the class */
	private Subject subject;
	
	/** Subject of the class */
	private Teacher teacher;

	/** Class of the subject */
	private Set<Review> reviews = new HashSet<Review>(0);
	
	/**
	 * Instantiates a new class entity
	 */
	public Clazz() {
		super();
	}

	/**
	 * Instantiates a new class entity
	 * 
	 * @param id:
	 *            The id of class
	 */
	public Clazz(int id) {
		super();
		this.id = id;
	}
	
	/**
	 * Instantiates a new class entity
	 */
	public Clazz(int id, String semester, String room, Subject subject, Teacher teacher, Set<Review> reviews) {
		super();
		this.id = id;
		this.semester = semester;
		this.room = room;
		this.subject = subject;
		this.teacher = teacher;
		this.reviews = reviews;
	}
	
	
	/**
	 * Setter and getter methods
	 */
	@Id
	@TableGenerator(name = "gen_id", table = "HIBERNATE_GEN_ID", pkColumnName = "GEN_NAME", valueColumnName = "GEN_VALUE", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "gen_id")
	@Column(name = "class_id", unique = true, nullable = false, precision = 22, scale = 0)
	public int getId() {
		return this.id;
	}
	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "semester", length = 40)
	public String getSemester() {
		return semester;
	}
	public void setSemester(String semester) {
		this.semester = semester;
	}
	
	@Column(name = "room", length = 5)
	public String getRoom() {
		return room;
	}
	public void setRoom(String room) {
		this.room = room;
	}

	@ManyToOne
	@JoinColumn(name = "subject_id", nullable = false)
	public Subject getSubject() {
		return subject;
	}
	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	@ManyToOne
	@JoinColumn(name = "teacher_id", nullable = false)
	public Teacher getTeacher() {
		return teacher;
	}
	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clazz")
	@JsonIgnore
	public Set<Review> getReviews() {
		return reviews;
	}
	public void setReviews(Set<Review> reviews) {
		this.reviews = reviews;
	}
}

