package promn.dao.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
* Amsubject generated by hbm2java
* 
*           The class Subject
*/

@Entity(name = "Subject")
@Table(name = "Subject")
public class Subject implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/** The id of the subject */
	private int id;

	/** The name of the subject */
	private String name;
	
	/** Class of the subject */
	private Set<Clazz> classes = new HashSet<Clazz>(0);

	/**
	 * Instantiates a new subject entity
	 */
	public Subject() {
		super();
	}

	/**
	 * Instantiates a new subject entity
	 * 
	 * @param id:
	 *            The id of subject
	 */
	public Subject(int id) {
		super();
		this.id = id;
	}
	
	/**
	 * Instantiates a new subject entity
	 */
	public Subject(int id, String name, Set<Clazz> classes) {
		super();
		this.id = id;
		this.name = name;
		this.classes = classes;
	}
	
	
	/**
	 * Setter and getter methods
	 */
	@Id
	@TableGenerator(name = "gen_id", table = "HIBERNATE_GEN_ID", pkColumnName = "GEN_NAME", valueColumnName = "GEN_VALUE", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "gen_id")
	@Column(name = "subject_id", unique = true, nullable = false, precision = 22, scale = 0)
	public int getId() {
		return this.id;
	}
	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "subject_name", length = 40)
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subject")
	@JsonIgnore
	public Set<Clazz> getClasses() {
		return classes;
	}
	public void setClasses(Set<Clazz> classes) {
		this.classes = classes;
	}
}

