package promn.dao.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
* Amteacher generated by hbm2java
* 
* @modified 24/04/2019
* @modifier ThinhLH
* 
*           The class Teacher
*/

@Entity(name = "Teacher")
@Table(name = "Teacher")
public class Teacher implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/** The id of the teacher */
	private int id;

	/** The name of the teacher */
	private String name;

	/** The age of the teacher */
	private int age;
	
	/** The address of the teacher */
	private String address;

	/** The phoneNumber of the teacher */
	private String phoneNumber;

	/** The school modified of the teacher */
	private String school;

	/** The email of the teacher */
	private String email;

	/** The achivement of the teacher */
	private String achievement;
	
	/** The imageUrl of the teacher */
	private String imageUrl;
	
	/** Class of the teacher */
	private Set<Clazz> classes = new HashSet<Clazz>(0);

	/**
	 * Instantiates a new teacher entity
	 */
	public Teacher() {
		super();
	}

	/**
	 * Instantiates a new teacher entity
	 * 
	 * @param id:
	 *            The id of teacher
	 */
	public Teacher(int id) {
		super();
		this.id = id;
	}
	
	/**
	 * Instantiates a new teacher entity
	 */
	public Teacher(int id, String name, int age, String address, String phoneNumber, String school, String email,
			String achievement, String imageUrl, Set<Clazz> classes) {
		super();
		this.id = id;
		this.name = name;
		this.age = age;
		this.address = address;
		this.phoneNumber = phoneNumber;
		this.school = school;
		this.email = email;
		this.achievement = achievement;
		this.imageUrl = imageUrl;
		this.classes = classes;
	}
	
	
	/**
	 * Setter and getter methods
	 */
	@Id
	@TableGenerator(name = "gen_id", table = "HIBERNATE_GEN_ID", pkColumnName = "GEN_NAME", valueColumnName = "GEN_VALUE", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "gen_id")
	@Column(name = "teacher_id", unique = true, nullable = false, precision = 22, scale = 0)
	public int getId() {
		return this.id;
	}
	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "teacher_name", length = 40)
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "teacher_age")
	public int getAge() {
		return age;
	}
	public void setAge(int age) {
		this.age = age;
	}
	
	@Column(name = "address", length = 100)
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone_num", length = 12)
	public String getPhoneNumber() {
		return phoneNumber;
	}
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "school", length = 100)
	public String getSchool() {
		return school;
	}
	public void setSchool(String school) {
		this.school = school;
	}

	@Column(name = "email", length = 20)
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	
	@Column(name = "achievements")
	public String getAchievement() {
		return achievement;
	}
	public void setAchievement(String achivement) {
		this.achievement = achivement;
	}

	@Column(name = "teacher_image", length = 40)
	public String getImageUrl() {
		return imageUrl;
	}
	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teacher")
	@JsonIgnore
	public Set<Clazz> getClasses() {
		return classes;
	}
	public void setClasses(Set<Clazz> classes) {
		this.classes = classes;
	}
}

