package promn.dao.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
* Amuser generated by hbm2java
* 
*           The class User
*/

@Entity(name = "Users")
@Table(name = "SystemUser")
public class User implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/** The id of the user */
	private int id;

	/** The name of the user */
	private String name;
	
	/** The password of the user */
	private String password;
	
	/** The imageUrl of the user */
	private String imageUrl;
	
	/** The studentId of the user */
	private int role;
	
	/** The studentId of the user */
	private int typeLogin;
	
	/** Review of the user */
	private Set<Review> reviews = new HashSet<Review>(0);
	
	/** Review of the user */
	private Set<Report> reports = new HashSet<Report>(0);

	/**
	 * Instantiates a new user entity
	 */
	public User() {
		super();
	}

	/**
	 * Instantiates a new user entity
	 * 
	 * @param id:
	 *            The id of user
	 */
	public User(int id) {
		super();
		this.id = id;
	}
	
	/**
	 * Instantiates a new user entity
	 */
	public User(int id, String name, String password, String imageUrl, int role, int typeLogin, Set<Review> reviews,
			Set<Report> reports) {
		super();
		this.id = id;
		this.name = name;
		this.password = password;
		this.imageUrl = imageUrl;
		this.role = role;
		this.typeLogin = typeLogin;
		this.reviews = reviews;
		this.reports = reports;
	}
	
	
	/**
	 * Setter and getter methods
	 */
	@Id
	@TableGenerator(name = "gen_id", table = "HIBERNATE_GEN_ID", pkColumnName = "GEN_NAME", valueColumnName = "GEN_VALUE", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "gen_id")
	@Column(name = "user_id", unique = true, nullable = false, precision = 22, scale = 0)
	public int getId() {
		return this.id;
	}
	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "username", length = 40)
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "password", length = 40)
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "avatar", length = 40)
	public String getImageUrl() {
		return imageUrl;
	}
	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "role")
	public int getRole() {
		return role;
	}
	public void setRole(int role) {
		this.role = role;
	}

	@Column(name = "type_login")
	public int getTypeLogin() {
		return typeLogin;
	}
	public void setTypeLogin(int typeLogin) {
		this.typeLogin = typeLogin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	@JsonIgnore
	public Set<Review> getReviews() {
		return reviews;
	}
	public void setReviews(Set<Review> reviews) {
		this.reviews = reviews;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	@JsonIgnore
	public Set<Report> getReports() {
		return reports;
	}
	public void setReports(Set<Report> reports) {
		this.reports = reports;
	}
}

